mysql:
    container_name: my_mysql
    build: mysql
    environment:
        - MYSQL_DATABASES=khabared_ucation
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_HOST=127.0.0.1
        - MYSQL_PORT=3306
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
        - MYSQL_MY_DATABASE=khabared_ucation
    ports:
        - "3306:3306"
    volumes:
        - "./volumes/mysql:/var/lib/mysql"
